image: gcc

stages:
  - build
  - deploy

build:
  stage: build
  before_script: 
    - apt update && apt -y install make autoconf build-essential
    - uname -a
  script: "gcc spdynUpdater.c -o releases/spdynu"