image: gcc
build_x64:
  stage: build
  before_script: 
    - apt update && apt -y install make autoconf build-essential gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu
  script: gcc spdynUpdater.c -o spdynu_x64 && arm-linux-gnueabihf-gcc spdynUpdater.c -o spdynu_armhf && aarch64-linux-gnu-gcc spdynUpdater.c -o spdynu_arm64
  artifacts:
    paths:
      - spdynu_x64
      - spdynu_armhf
      - spdynu_arm64