image: gcc
stages:
  - build
  - deploy

build:
  stage: build
  before_script: 
    - apt update && apt -y install make autoconf build-essential cmake
    - ls
  script: gcc spdynUpdater.c -o releases/spdynu
  artifacts:
    paths:
      - releases/spdynu