image: debian:stretch
build_x64:
  stage: build
  before_script: 
    - apt update && apt -y install make autoconf build-essential
  script: gcc spdynUpdater.c -o spdynu_x64
  artifacts:
    paths:
      - spdynu_x64
      
build_armhf:
  stage: build
  before_script: 
    - apt update && apt -y install make autoconf build-essential gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu
  script: arm-linux-gnueabihf-gcc spdynUpdater.c -o spdynu_armhf
  artifacts:
    paths:
      - spdynu_armhf