stages: 
    - build-stretch-amd64
    - build-buster-amd64
    - build-xenial-amd64
    - build-bionic-amd64

build-stretch-amd64:
   stage: build-stretch-amd64
   image: amd64/debian:stretch
   script:
   - apt update
   - apt-get -y upgrade
   - apt-get -y install apt-utils build-essential devscripts debhelper
   - gcc spdynUpdater.c -o spdynu
   - chmod u+x spdyn
   - dpkg-buildpackage -us -uc
   - mkdir -p build/
   - mv ../*.deb build/
   - cd build
   - mv spdynu_2018.07_all.deb spdynu-stretch-amd64.deb
   artifacts:
       name: "spdynu"
       paths:
        - build/*

build-buster-amd64:
   stage: build-buster-amd64
   image: amd64/debian:buster
   script:
   - apt update
   - apt-get -y upgrade
   - apt-get -y install apt-utils build-essential devscripts debhelper
   - gcc spdynUpdater.c -o spdynu
   - chmod u+x  spdynu
   - dpkg-buildpackage -us -uc
   - mkdir -p build/
   - mv ../*.deb build/
   - cd build
   - mv spdynu_2018.07_all.deb spdynu-buster-amd64.deb
   artifacts:
       name: "spdynu"
       paths:
        - build/*

build-xenial-amd64:
   stage: build-xenial-amd64
   image: amd64/ubuntu:xenial
   script:
   - apt update
   - apt-get -y upgrade
   - apt-get -y install apt-utils build-essential devscripts debhelper
   - gcc spdynUpdater.c -o spdynu
   - chmod u+x spdynu
   - dpkg-buildpackage -us -uc -d
   - mkdir -p build/
   - mv ../*.deb build/
   - cd build
   - mv spdynu_2018.07_all.deb spdynu-xenial-amd64.deb
   artifacts:
       name: "spdynu"
       paths:
        - build/*

build-bionic-amd64:
   stage: build-bionic-amd64
   image: amd64/ubuntu:bionic
   script:
   - apt update
   - apt-get -y upgrade
   - apt-get -y install apt-utils build-essential devscripts debhelper
   - gcc spdynUpdater.c -o spdynu
   - chmod u+x  spdynu
   - dpkg-buildpackage -us -uc -d
   - mkdir -p build/
   - mv ../*.deb build/
   - cd build
   - mv spdynu_2018.07_all.deb spdynu-bionic-amd64.deb
   artifacts:
       name: "spdynu"
       paths:
        - build/*

