stages:
  - build
  - deploy

build:
  stage: build
  before_script: 
    - apt update && apt -y install make autoconf build-essential cmake
    - uname -a
  script: cmake spdynUpdater.c -o releases/spdynu