image: gcc

build:
  stage: build
  before_script: 
    - apt update && apt -y install make autoconf build-essential
    - cd releases
 
script: gcc spdynUpdater.c -o releases/spdynu
  
artifacts:
    paths:
      - public
only:
  - master
